template: |
  $CHANGES

categories:
  - title: "🚀 新增"
    labels:
      - feat
  - title: "🐛 修复"
    labels:
      - fix
  - title: "🔧 优化"
    labels:
      - refactor
      - perf
      - style

exclude-labels:
  - docs
  - test
  - chore

change-template: '- $TITLE'

version-resolver:
  minor:
    labels:
      - feat
  patch:
    labels:
      - fix
      - refactor
      - perf
      - style
  default: patch
